### ISSUE TITLE
Error with running `pg_replication_slot_advance()`

### ISSUE THREAD

**Issue by mitchbregs** [debezium/debezium-server#3]
Hello there,

For background, we are using Postgres11. The `debezium` user we have created for replication has `rds_replication` enabled, following these [docs](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-on-amazon-rds). 

As for the warn message, we are definitely using an RDS version that is compatible with this function. However, the error statement where it must be a superuser or replication role is concerning. When I run a query to see all roles associated to my user, I have `rds_replication` enabled. As for the docs, I am concerned this might be the problem: https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-replication-user-privileges

I don't feel comfortable granting the `debezium` user superuser privileges. So I can have the superuser create the Postgres publication named `dbz_publication`. Will this solve all these issues? Or am I looking at an entirely different issue?

PS - this error happens after the initial sync and then we are stuck hanging.

```
2023-01-30 22:07:06,082 INFO  [io.deb.con.pos.con.PostgresReplicationConnection] (debezium-postgresconnector-mydb-change-event-source-coordinator) Seeking to LSN{1B0F/D0002D68} on the replication slot with command SELECT pg_replication_slot_advance('debezium', '1B0F/D0002D68')
2023-01-30 22:07:06,085 WARN  [io.deb.con.pos.con.PostgresReplicationConnection] (debezium-postgresconnector-mydb-change-event-source-coordinator) Unable to use pg_replication_slot_advance() function. The Postgres server is likely on an old RDS version: org.postgresql.util.PSQLException: ERROR: must be superuser or replication role to use replication slots
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.validateSlotIsInExpectedState(PostgresReplicationConnection.java:365)
	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.startStreaming(PostgresReplicationConnection.java:328)
	at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.execute(PostgresStreamingChangeEventSource.java:137)
	at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.execute(PostgresStreamingChangeEventSource.java:41)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:174)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:141)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by jpechane** [comment]
@mitchbregs Hi, this is only warning, not error. If there is no activity than the root cause is something else. Please use chat/mailing list for questions. I amo going to close this one as we use Jira for issue tracking.
